-- Create Source Stream from Kafka topic

CREATE STREAM BIKE_HIRE_SRC (
    id          VARCHAR KEY,
    name        VARCHAR,
    bikes       INT,
    empty_docks INT,
    total_docks INT
) WITH (
    KAFKA_TOPIC='bike.hire',
    VALUE_FORMAT='AVRO'
);


-- Quick query 
SET 'auto.offset.reset' = 'earliest';

SELECT 
    TIMESTAMPTOSTRING(ROWTIME,'yyyy-MM-dd HH:mm:ss','Europe/London') AS LASTUPDATE,
    ID,
    NAME,
    BIKES,
    EMPTY_DOCKS,
    TOTAL_DOCKS
FROM BIKE_HIRE_SRC
EMIT CHANGES
LIMIT 5;


-- Stream for downstream processing

CREATE STREAM BIKE_HIRE_CLEANED AS
SELECT
    ID,
    NAME,
    BIKES,
    EMPTY_DOCKS,
    TOTAL_DOCKS
FROM BIKE_HIRE_SRC
EMIT CHANGES;


-- Quick Query 

SELECT * 
FROM BIKE_HIRE_CLEANED
EMIT CHANGES
LIMIT 5;


--  Materialized Table to hold latest bike status per station

CREATE TABLE BIKE_HIRE_LATEST AS
SELECT
    ID,
    LATEST_BY_OFFSET(NAME) AS NAME,
    LATEST_BY_OFFSET(BIKES) AS BIKES,
    LATEST_BY_OFFSET(EMPTY_DOCKS) AS EMPTY_DOCKS,
    LATEST_BY_OFFSET(TOTAL_DOCKS) AS TOTAL_DOCKS,
    LATEST_BY_OFFSET(ROWTIME) AS LAST_UPDATE_TS 
FROM BIKE_HIRE_SRC
GROUP BY ID;


SELECT * 
FROM BIKE_HIRE_CLEANED
EMIT CHANGES
LIMIT 5;


-- Query a specific station
SELECT
    TIMESTAMPTOSTRING(LAST_UPDATE_TS,'yyyy-MM-dd HH:mm:ss','Europe/London') AS TS,
    NAME,
    BIKES,
    EMPTY_DOCKS,
    TOTAL_DOCKS
FROM BIKE_HIRE_LATEST
WHERE ID='10'
EMIT CHANGES;

-- Low bike alert
CREATE STREAM LOW_BIKES AS
SELECT
    ID,
    NAME,
    BIKES,
    EMPTY_DOCKS,
    TOTAL_DOCKS
FROM BIKE_HIRE_SRC
WHERE BIKES < 5
EMIT CHANGES;


SELECT *
FROM LOW_BIKES
EMIT CHANGES
LIMIT 5;
